# Site settings
title: dumyCq Blog
SEOTitle: 常奇的博客 | dumyCq Blog
header-img: img/dc-linkenm-yinghua.jpg
email: Trynda_Chang@hotmail.com
description: "Dream will take me for a ride as long as I am in the prime of youth."
keyword: "dumyCq, dumy_c, CQ, dumyCq Blog, 常奇的博客, 常奇, matlab, mathwork, C++, Visual Studio 2017, signal processing, image processing, medical image processing"
url: "http://dumyCq.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/dumyCq/dumyCq.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "There is no such thing as a great talent without great will-power!"
sidebar-avatar: /img/self-photo.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     dumyCq
github_username:    dumyCq
facebook_username:  trynda.chang
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
#disqus_username:dumycq

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 845c91a7ca270fb7a640                            #生成的clientID
  clientSecret: 04c1f65ecda98e497b353f7d82bea024aa403f8c    #生成的clientSecret
  repo: dumyCq.github.io    #仓库名称
  owner: dumyCq    #github用户名
  admin: dumyCq
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-122332140-1'            # Format: UA-xxxxxx-xx
ga_domain: futuredumycq.tech              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



